blog/urls.py
from django.urls import path

from blog import views


# URL 네임스페이스 설정
app_name = 'blog'

urlpatterns = [
    # Post 상세페이지 URL 매핑
    # /blog/post/99/
    # <int: > : 정수형 숫자 매핑
    # post/[정수형 숫자]로 시작하는 페이지를 요청하면, 해당 정수형 숫자를 pk에 저장하고, PostDV 클래스 뷰를 호출
    # <int: > : 정수형 숫자 매핑
    # 예를 들어, 만일 http://localhost:8000/post/2/ 페이지가 요청되면
    # 여기에 등록한 매핑 룰에 의해 http://localhost:8000/post/<int:pk>/ 가 적용되어,
    # pk 에 2가 저장되고, PostDV 클래스 뷰도 실행.
    # name='post_detail' : 해당 URL에 대해 URL 별칭 설정
    path('post/<int:pk>/', views.PostDV.as_view(), name='post_detail'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite.views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    # 홈 페이지 URL 매핑
    # HomeView.as_view() : 클래스형 뷰 형식
    # / 로 시작하는 페이지를 요청하면, (views의) HomeView 클래스 뷰를 호출
    # name='home' : 해당 URL에 대해 URL 별칭 설정
    path('', HomeView.as_view(), name='home'),
    # blog/ 로 시작하는 페이지를 요청하면, blog/urls.py 파일의 매핑 정보를 읽어서 처리하도록 함
    path('blog/', include('blog.urls')),
]

# 사이트에 업로드한 미디어 파일을 불러오기 위한 코드
# (장고가 제공하는) static 함수에 의해서, (settings 파일에서 정의한) MEDIA_URL이 들어오면 MEDIA_ROOT로 정의한 폴더에서 해당 미디어 파일을 찾아 처리하게 됨
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# blog 앱에서 필요한 모델(테이블)들을 정의

from django.db import models


# 포스트 모델(테이블)
class Post(models.Model):
    # 카테고리 모델을 속성으로 연결
    # models.ForeignKey('Category', ) : Category 모델을 외래키로 연결
    # on_delete=models.SET_NULL : 연결된 테이블(Category)의 해당 레코드가 삭제되는 경우, 해당 테이블(Post) 레코드의 해당 컬럼(category)을 NULL로 채우라는 의미
    # blank=True, null=True : 해당 컬럼의 값으로 공백값(null, '')이 저장되는 것을 허용
    # blank=True와 null=True의 차이
    # blank=True : 필드가 폼(입력 양식)에서 empty한 상태로 저장되는 것을 허용한다. DB column에 해당 값은 빈 폼의 형태, 즉 ''로 저장됨
    # null = True : DB column에 해당 값은 null로 저장됨
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, blank=True, null=True)
    # 태그 모델을 속성으로 연결
    # Tag 모델을 ManyToManyField 관계로 연결. 다대다(N:N) 관계
    tags = models.ManyToManyField('Tag', blank=True)
    # 제목 컬럼
    # models.CharField('TITLE', ) : 해당 컬럼들의 별칭으로 임의로 지정해 줌
    # 최대 50자
    title = models.CharField('TITLE', max_length=50)
    # 한 줄 요약 컬럼
    # models.CharField('DESCRIPTION', ) : 해당 컬럼들의 별칭으로 임의로 지정해 줌
    # CharField인 경우, null=True를 설정하지 않는 것이 좋다. 그 이유는, 값이 존재하지 않으면 null이 아닌 ''(empty string)이 저장되게 하기 위해
    # help_text='simple one-line text.' : 해당 컬럼에 대한 설명문 작성
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple one-line text.')
    # 이미지 컬럼
    # upload_to='blog/%Y/%m/' : 해당 이미지 파일이 저장될 디렉터리의 경로 지정
    image = models.ImageField('IMAGE', upload_to='blog/%Y/%m/', blank=True, null=True)
    # 내용 컬럼
    content = models.TextField('CONTENT')
    # 작성 일시 컬럼
    # auto_now_add=True : django model이 최초 저장(insert) 시에만 현재 날짜(date.today())를 적용
    create_dt = models.DateTimeField('CREATE DT', auto_now_add=True)
    # 수정 일시 컬럼
    # auto_now=True : django model이 save될 때마다 현재 날짜(date.today()) 로 갱신
    update_dt = models.DateTimeField('UPDATE DT', auto_now=True)
    # 좋아요 기능 컬럼
    # default=0 : 컬럼이 생성될 때 해당 컬럼에 값이 주어지지 않으면, 값을 0으로 채워줌
    like = models.PositiveSmallIntegerField('LIKE', default=0)

    # __str__ 메서드(string 메서드)
    def __str__(self):
        return self.title  # 제목 표시

# 카테고리 모델(테이블)
class Category(models.Model):
    # 이름 컬럼
    # unique=True : 중복된 값이 생기지 않도록 설정
    name = models.CharField(max_length=50, unique=True)
    # 한 줄 요약 컬럼
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple one-line text.')

    def __str__(self):
        return self.name  # 이름 표시

# 태그 모델(테이블)
class Tag(models.Model):
    # 이름 컬럼
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name  # 이름 표시

# 댓글 모델(테이블)
class Comment(models.Model):
    # 포스트 모델을 속성으로 연결
    # models.ForeignKey('Category', ) : Category 모델을 외래키로 연결
    # on_delete=models.CASCADE : Post 테이블의 레코드가 삭제되면, Comment 테이블의 레코드도 삭제되도록 설정
    # models.ForeignKey(Post, ) : 앞에서 Post 테이블이 정의되어 있는 경우 이와 같이 따옴표를 붙이지 않고 Post라고 작성해도 된다.
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True, null=True)
    # 내용 컬럼
    content = models.TextField('CONTENT')
    # 작성 일시 컬럼
    create_dt = models.DateTimeField('CREATE DT', auto_now_add=True)
    # 수정 일시 컬럼
    update_dt = models.DateTimeField('UPDATE DT', auto_now=True)


    # 파이썬의 @property 문법을 사용해 메서드를 필드로 정의
    @property
    # 댓글 내용으로부터 10글자를 가져오는 short_content 메서드 정의
    def short_content(self):
        # 댓글(content) 내용으로부터 10글자만 가져온다.
        return self.content[:10]

    # Comment 모델에는 title이나 name과 같은 컬럼이 없어서, 임의의 메서드를 직접 정의해서 사용할 것이다.
    def __str__(self):
        # 직접 정의한 short_content 메서드(필드)를 string 메서드에 사용
        return self.short_content  # 댓글의 내용(댓글 내용의 10글자) 표시

blog/views.py
from django.views.generic import DetailView

from blog.models import Post


# Post 상세페이지 관련 클래스 뷰
# DetailView를 상속받음
class PostDV(DetailView):
    # 대상 모델(테이블) 지정  # blog/models.py의 Post 모델
    model = Post
    # 해당 클래스 뷰에 관련 템플릿 파일(blog/post_detail.html) 지정
    template_name = 'blog/post_detail.html'

mysite/views.py
# 클래스형 뷰 형식

from django.views.generic import TemplateView


# 홈 페이지 관련 클래스 뷰
# TemplateView를 상속받음
class HomeView(TemplateView):
    # 해당 클래스 뷰에 관련 템플릿 파일(home.html) 지정
    template_name = 'home.html'

templates/base.html
<!-- 모든 템플릿들의 기본 틀이 되는 base.html 템플릿. 표준 HTML 구조로 작성 -->
{% load static %}  {# 해당 템플릿에서 스태틱 파일을 사용하기 위해 {% load static%} 태그 삽입 #} 
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            <!-- 기본 템플릿 안에 삽입될 제목 Start -->
            {% block title %}{% endblock %}
            <!-- 기본 템플릿 안에 삽입될 제목 End -->
        </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script
            src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
            crossorigin="anonymous"
        ></script>
        <!-- Google fonts-->
        <link
            href="https://fonts.googleapis.com/css?family=Montserrat:400,700"
            rel="stylesheet"
            type="text/css"
        />
        <link
            href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700"
            rel="stylesheet"
            type="text/css"
        />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <!-- 기본 템플릿 안에 삽입될 스타일 Start -->
        {% block extra-style %}{% endblock %}
        <!-- 기본 템플릿 안에 삽입될 스타일 End -->
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <div class="navbar-brand">Vue - Django Web Programming</div>  {# 사이트 제목 #}
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarResponsive"
                    aria-controls="navbarResponsive"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        {# 홈 메뉴 #}
                        <li class="nav-item">  
                            {# bootstrap ScrollSpy 기능이 적용되도록 하기 위해 data-bs-target 속성을 추가해 적용해줌. href 기능도 가능하지만, 우리가 Fragment뿐만 아니라 url도 같이 지정해준 상태여서 scrollspy가 적용되지 않았음. #}
                            <a class="nav-link" data-bs-target="#page-top" href="{% url 'home' %}#page-top">Home</a>  {# page-top : 홈 메뉴 클릭 시, 페이지 상위 부분으로 이동 #}
                        </li>
                        {# 블로그 메뉴 #}
                        <li class="nav-item">
                            <a class="nav-link" data-bs-target="#blog" href="{% url 'home' %}#blog">Blog</a>
                        </li>
                        {# 자기소개 메뉴 #}
                        <li class="nav-item">
                            <a class="nav-link" data-bs-target="#iam" href="{% url 'home' %}#iam">Iam</a>
                        </li>
                        {# 관리자 메뉴 #}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>  {# 관리자 메뉴 클릭 시, 관리자 페이지 URL로 이동 #}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->  {# 홈 메뉴 #}
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">Welcome To My Blog!</div>
                <div class="masthead-heading text-uppercase">
                    저의 일상을 기록하고 있습니다.
                </div>
            </div>
        </header>
        <!-- 기본 템플릿 안에 삽입될 본문 Start -->
        {% block content %}{% endblock %}
        <!-- 기본 템플릿 안에 삽입될 본문 End -->

        <!-- 기본 템플릿 안에 삽입될 Footer Start -->
        {% block footer %}{% endblock %}
        <!-- 기본 템플릿 안에 삽입될 Footer End -->

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- 기본 템플릿 안에 삽입될 JS Start -->
        {% block extra-script %}{% endblock %}
        <!-- 기본 템플릿 안에 삽입될 JS End -->
    </body>
</html>

templates/blog/post_detail.html
<!-- Post 상세페이지 관련 템플릿 -->
{% extends 'base.html' %}  {# base.html 템플릿 상속 #}

{% load static %}  {# 해당 템플릿에서 스태틱 파일을 사용하기 위해 {% load static%} 태그 삽입 #} 

{% block title %}home.html{% endblock %}  {# base.html 제목 오버라이딩 #}

{% block content %}  {# base.html 본문 오버라이딩 #}
<!-- Post Detail Grid-->  {# Post 상세보기 페이지 #}
<section class="page-section" id="post">
    <div class="container">
        <div class="row">
            <!-- Post title-->
            <h1 class="fw-bolder mb-1">Welcome to Blog Post!</h1>
            <hr>
            <p>
                <span>2022-10-07 &emsp;</span>
                <i class="fas fa-copyright"></i>  {# 웹 폰트 아이콘 #}
                <span>IT &emsp;</span>
                <i class="fas fa-tag"></i>
                <span>django python &emsp;</span>
                <i class="fas fa-heart"></i>
                <span>5 &emsp;</span>
            </p>
            <hr>
        </div>
        <div class="row">
            <div class="col-lg-8">
                <!-- Post content-->
                <article>
                    <!-- Preview image figure-->
                    <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>
                    <!-- Post content-->
                    <div class="mb-5">
                        <p class="fs-5 mb-4">Science is an enterprise that should be cherished as an activity of the free human mind. Because it transforms who we are, how we live, and it gives us an understanding of our place in the universe.</p>
                        <p class="fs-5 mb-4">The universe is large and old, and the ingredients for life as we know it are everywhere, so there's no reason to think that Earth would be unique in that regard. Whether of not the life became intelligent is a different question, and we'll see if we find that.</p>
                        <p class="fs-5 mb-4">If you get asteroids about a kilometer in size, those are large enough and carry enough energy into our system to disrupt transportation, communication, the food chains, and that can be a really bad day on Earth.</p>
                        <h2 class="fw-bolder mb-4 mt-5">I have odd cosmic thoughts every day</h2>
                        <p class="fs-5 mb-4">For me, the most fascinating interface is Twitter. I have odd cosmic thoughts every day and I realized I could hold them to myself or share them with people who might be interested.</p>
                        <p class="fs-5 mb-4">Venus has a runaway greenhouse effect. I kind of want to know what happened there because we're twirling knobs here on Earth without knowing the consequences of it. Mars once had running water. It's bone dry today. Something bad happened there as well.</p>
                    </div>
                </article>
                <!-- Comments section-->  {# 댓글 #}
                <div class="mb-5">
                    <div class="card bg-light">
                        <div class="card-body">
                            <!-- Comment form-->
                            <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
                            <!-- Comment with nested comments-->
                            <div class="d-flex mb-4">
                                <!-- Parent comment-->
                                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                <div class="ms-3">
                                    <div class="fw-bold">Commenter Name</div>  {# 댓글 작성자 #}
                                    If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                                </div>
                            </div>
                            <!-- Single comment-->
                            <div class="d-flex">
                                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                <div class="ms-3">
                                    <div class="fw-bold">2022-10-07 14:53:16</div>  {# 댓글 수정 시간 #}
                                    When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Side widgets-->  {# 위젯 #}
            <div class="col-lg-4">
                <div class="card mb-4">
                    <div class="card-header">Prev Post</div>  {# 이전 Post #}
                    <div class="card-body">
                        This is previous post title
                    </div>
                </div>
                <div class="card mb-4">
                    <div class="card-header">Next Post</div>  {# 다음 Post #}
                    <div class="card-body">
                        This is previous post title
                    </div>
                </div>
                <!-- Categories widget-->
                <div class="card mb-4">
                    <div class="card-header">Categories</div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <ul class="list-unstyled mb-0">
                                    <li><a href="#!">Web Design</a></li>
                                    <li><a href="#!">HTML</a></li>
                                    <li><a href="#!">Freebies</a></li>
                                </ul>
                            </div>
                            <div class="col-sm-6">
                                <ul class="list-unstyled mb-0">
                                    <li><a href="#!">JavaScript</a></li>
                                    <li><a href="#!">CSS</a></li>
                                    <li><a href="#!">Tutorials</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Categories widget-->
                <div class="card mb-4">
                    <div class="card-header">Tag Cloud</div>  {# Tag cloud #}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <ul class="list-unstyled mb-0">
                                    <li><a href="#!">Web Design</a></li>
                                    <li><a href="#!">HTML</a></li>
                                    <li><a href="#!">Freebies</a></li>
                                </ul>
                            </div>
                            <div class="col-sm-6">
                                <ul class="list-unstyled mb-0">
                                    <li><a href="#!">JavaScript</a></li>
                                    <li><a href="#!">CSS</a></li>
                                    <li><a href="#!">Tutorials</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/home.html
<!-- 홈 페이지 관련 템플릿 -->
{% extends 'base.html' %}  {# base.html 템플릿 상속 #}

{% load static %}  {# 해당 템플릿에서 스태틱 파일을 사용하기 위해 {% load static%} 태그 삽입 #} 

{% block title %}home.html{% endblock %}  {# base.html 제목 오버라이딩 #}

{% block content %}  {# base.html 본문 오버라이딩 #}
<!-- Blog Grid-->  {# 블로그 메뉴 #}
<section class="page-section bg-light" id="blog">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Blog list</h2>
            <h3 class="section-subheading text-muted">
                블로그 리스트입니다.
            </h3>
        </div>
        <div class="row">
            <div class="col-lg-4 col-sm-6 mb-4">
                <!-- Blog item 1-->
                <div class="blog-item">
                    <a
                        class="blog-link"
                        {# Blog list에서 블로그 하나를 클릭하면 Post 상세페이지(post_detail)를 불러오도록 연결 #}
                        href="{% url 'blog:post_detail' 1 %}"
                    >
                        <div class="blog-hover">
                            <div class="blog-hover-content">
                                <i class="fas fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img
                            class="img-fluid"
                            src="{% static 'assets/img/blog/1.jpg' %}"
                            alt="..."
                        />
                    </a>
                    <div class="blog-caption">
                        <div class="blog-caption-heading">
                            Threads
                        </div>
                        <div
                            class="blog-caption-subheading text-muted"
                        >
                            Illustration
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6 mb-4">
                <!-- Blog item 2-->
                <div class="blog-item">
                    <a
                        class="blog-link"
                        data-bs-toggle="modal"
                        href="#blogModal2"
                    >
                        <div class="blog-hover">
                            <div class="blog-hover-content">
                                <i class="fas fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img
                            class="img-fluid"
                            src="{% static 'assets/img/blog/2.jpg' %}"
                            alt="..."
                        />
                    </a>
                    <div class="blog-caption">
                        <div class="blog-caption-heading">
                            Explore
                        </div>
                        <div
                            class="blog-caption-subheading text-muted"
                        >
                            Graphic Design
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6 mb-4">
                <!-- Blog item 3-->
                <div class="blog-item">
                    <a
                        class="blog-link"
                        data-bs-toggle="modal"
                        href="#blogModal3"
                    >
                        <div class="blog-hover">
                            <div class="blog-hover-content">
                                <i class="fas fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img
                            class="img-fluid"
                            src="{% static 'assets/img/blog/3.jpg' %}"
                            alt="..."
                        />
                    </a>
                    <div class="blog-caption">
                        <div class="blog-caption-heading">
                            Finish
                        </div>
                        <div
                            class="blog-caption-subheading text-muted"
                        >
                            Identity
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Iam-->  {# 자기소개 메뉴 #}
<section class="page-section bg-light" id="iam">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">
                Youngjin Jung
            </h2>
            <h3 class="section-subheading text-muted">
                안녕하세요 정영진입니다.
            </h3>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="iam-member mb-5">
                    <img
                        class="mx-auto rounded-circle"
                        src="{% static 'assets/img/iam/Mancity_Simpson.jpg' %}"
                        alt="..."
                        width="250" height="250"
                    />
                    <h4>Mancity Company</h4>
                    <p class="text-muted">Python Web Programmer</p>
                    <a
                        class="btn btn-dark btn-social mx-2"
                        href="#!"
                        aria-label="Parveen Anand Twitter Profile"
                        ><i class="fab fa-twitter"></i
                    ></a>
                    <a
                        class="btn btn-dark btn-social mx-2"
                        href="#!"
                        aria-label="Parveen Anand Facebook Profile"
                        ><i class="fab fa-facebook-f"></i
                    ></a>
                    <a
                        class="btn btn-dark btn-social mx-2"
                        href="#!"
                        aria-label="Parveen Anand LinkedIn Profile"
                        ><i class="fab fa-linkedin-in"></i
                    ></a>
                </div>
            </div>
            <div class="col-lg-8"></div>
                <div class="mb-5">
                    <h4>정보보호학과 전공</h4>
                    <p class="text-muted">
                        Do dolore duis id voluptate reprehenderit dolore do deserunt. Velit est dolor reprehenderit sit esse
                        irure velit voluptate esse enim. Reprehenderit qui sit cillum voluptate labore deserunt excepteur nulla dolor.
                    </p>
                </div>
                <div class="mb-5">
                    <h4>파이썬 장고 주니어 개발자</h4>
                    <p class="text-muted">
                        Do dolore duis id voluptate reprehenderit dolore do deserunt. Velit est dolor reprehenderit sit esse
                        irure velit voluptate esse enim. Reprehenderit qui sit cillum voluptate labore deserunt excepteur nulla dolor.
                    </p>  
                </div>
                <div class="mb-5">
                    <h4>주니어 데이터엔지니어</h4>
                    <p class="text-muted">
                        Do dolore duis id voluptate reprehenderit dolore do deserunt. Velit est dolor reprehenderit sit esse
                        irure velit voluptate esse enim. Reprehenderit qui sit cillum voluptate labore deserunt excepteur nulla dolor.
                    </p>  
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block footer %}  {# base.html Footer 오버라이딩 #}
<!-- Footer-->
<footer class="footer py-4">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-4 text-lg-start">
                Copyright &copy; Your Website 2022
            </div>
            <div class="col-lg-4 my-3 my-lg-0">
                <a
                    class="btn btn-dark btn-social mx-2"
                    href="#!"
                    aria-label="Twitter"
                    ><i class="fab fa-twitter"></i
                ></a>
                <a
                    class="btn btn-dark btn-social mx-2"
                    href="#!"
                    aria-label="Facebook"
                    ><i class="fab fa-facebook-f"></i
                ></a>
                <a
                    class="btn btn-dark btn-social mx-2"
                    href="#!"
                    aria-label="LinkedIn"
                    ><i class="fab fa-linkedin-in"></i
                ></a>
            </div>
            <div class="col-lg-4 text-lg-end">
                <a class="link-dark text-decoration-none me-3" href="#!"
                    >Privacy Policy</a
                >
                <a class="link-dark text-decoration-none" href="#!"
                    >Terms of Use</a
                >
            </div>
        </div>
    </div>
</footer>
{% endblock %}